apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: szl41ljcm-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: szl41ljcm-nodejs 
  name: szl41ljcm-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: szl41ljcm-nodejs 
